###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  postgres:
    image: postgres:13.6-alpine
    container_name: sponsor-console-postgres
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres


  postgres-test:
    image: postgres:13.6-alpine
    container_name: sponsor-console-postgres-test
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  webserver:
    image: nginx:alpine
    container_name: sponsor-console-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: sponsor-console-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/openssl.cnf:/etc/ssl/openssl.cnf
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=docker mode=debug"
      PHP_IDE_CONFIG: "serverName=docker"
  php-cli:
    build:
      context: phpdocker/php-fpm
      dockerfile: Dockerfile-cli
    container_name: sponsor-console-php-cli
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/openssl.cnf:/etc/ssl/openssl.cnf
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=docker mode=debug"
      PHP_IDE_CONFIG: "serverName=docker"

  composer:
    build: phpdocker/php-fpm
    container_name: sponsor-console-composer
    working_dir: /application
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini
    command: bash -c "php bin/console doctrine:migrations:migrate --no-interaction;composer install;"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

