monolog:
  channels: ['user_channel']
  handlers:
    #        main:
    #            type: fingers_crossed
    #            action_level: error
    #            handler: nested
    #            excluded_http_codes: [404, 405]
    #            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
    #        nested:
    #            type: stream
    #            path: php://stderr
    #            level: debug
    #            formatter: monolog.formatter.json
    #        console:
    #            type: console
    #            process_psr_3_messages: false
    #            channels: ["!event", "!doctrine"]
    user_handler:
      level: info
      type: rotating_file
      path: '%kernel.logs_dir%/user.log'
      channels: ['user_channel']
      max_files: 30
    main:
      type: fingers_crossed
      action_level: error
      excluded_http_codes: [ 404, 405 ]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      handler: grouped
      channels: ['!user_channel']
    grouped:
      type: group
      members: [ streamed, deduplicated ]
    streamed:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      max_files: 10
      channels: [ '!user_channel' ]
    deduplicated:
      type: deduplication
      handler: symfony_mailer
    symfony_mailer:
      type: symfony_mailer
      from_email: '%env(MAILER_MAIL_FROM)%'
      to_email: []
      subject: 'Ошибка! %%message%%'
      level: info
      formatter: monolog.formatter.html
      content_type: text/html
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine","!user_channel"]
